name: Build and Push Multi-arch Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: erreur32/homeassistant-dozzle-addon

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from config.yaml
        id: version
        run: |
          VERSION=$(grep -m 1 "version:" dozzle/config.yaml | awk '{print $2}' | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        strategy:
          matrix:
            arch: [amd64, aarch64, armv7]
        with:
          context: ./dozzle
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-${{ matrix.arch }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-${{ matrix.arch }}:latest
          platforms: |
            linux/${{ matrix.arch == 'aarch64' && 'arm64' || matrix.arch == 'armv7' && 'arm/v7' || matrix.arch }}
          build-args: |
            BUILD_ARCH=${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify images exist
        run: |
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-amd64:${{ env.VERSION }}
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-aarch64:${{ env.VERSION }}
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-armv7:${{ env.VERSION }}
          docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-amd64:${{ env.VERSION }}
          docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-aarch64:${{ env.VERSION }}
          docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-armv7:${{ env.VERSION }}
