name: Builder

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Permet de continuer même si une architecture échoue
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: aarch64
            platform: linux/arm64
          - arch: armv7
            platform: linux/arm/v7
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dozzle
          file: ./dozzle/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            BUILD_ARCH=${{ matrix.arch }}
          tags: |
            ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-${{ matrix.arch }}:latest
            ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-${{ matrix.arch }}:0.1.49
