name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: erreur32/homeassistant-dozzle-addon

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, armv7, armhf, aarch64, i386]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./dozzle
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-${{ matrix.arch }}:latest
          platforms: linux/${{ matrix.arch }}
          build-args: |
            BUILD_ARCH=${{ matrix.arch }} 