name: Builder

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture:
          - platform: "linux/amd64"
            build_arch: "amd64"
          - platform: "linux/arm64"
            build_arch: "aarch64"
          - platform: "linux/arm/v7"
            build_arch: "armv7"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./dozzle
          platforms: ${{ matrix.architecture.platform }}
          push: true
          build-args: |
            BUILD_ARCH=${{ matrix.architecture.build_arch }}
          tags: |
            ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-${{ matrix.architecture.build_arch }}:latest
            ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-${{ matrix.architecture.build_arch }}:0.1.49
