jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies (jq, curl, yq)
      run: sudo apt-get install -y jq curl

    - name: Install Go 1.24.0
      run: |
        curl -sSL https://go.dev/dl/go1.24.0.linux-amd64.tar.gz -o go.tar.gz
        sudo tar -C /usr/local -xzf go.tar.gz
        rm go.tar.gz
        echo "/usr/local/go/bin" >> $GITHUB_PATH
        go version  # Vérification de la version

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Extract `BUILD_FROM` from `build.yaml`
      id: extract_base
      run: echo "BUILD_FROM=$(yq eval '.build_from.amd64' dozzle/build.yaml)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/homeassistant-dozzle-addon"
        IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')  # ✅ Conversion en minuscules
        docker build --build-arg BUILD_FROM=$BUILD_FROM -t $IMAGE_NAME:latest -f dozzle/Dockerfile .
        docker build --build-arg BUILD_FROM=$BUILD_FROM -t $IMAGE_NAME:${{ github.sha }} -f dozzle/Dockerfile .

    - name: Push Docker image to GHCR
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/homeassistant-dozzle-addon"
        IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')  # ✅ Conversion en minuscules
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}
