name: Build and Push Docker Image

permissions:
  packages: write
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (jq, curl)
        run: sudo apt-get install -y jq curl

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/homeassistant-dozzle-addon"
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker build -t $IMAGE_NAME:latest -f Dockerfile .
          docker build -t $IMAGE_NAME:${{ github.sha }} -f Dockerfile .

      - name: Push Docker image to GHCR
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/homeassistant-dozzle-addon"
          IMAGE_NAME=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}
