name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build and Push the Docker image
      run: |
        IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/homeassistant-dozzle-addon

        # Build the image with "latest" and commit SHA tags
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest
        docker build . --file Dockerfile --tag $IMAGE_NAME:${{ github.sha }}

        # Push both tags
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}
