name: Sign Docker Images

on:
  workflow_run:
    workflows: ["Build and Push Multi-arch Docker Images"]
    types:
      - completed

jobs:
  sign:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from config.yaml
        id: version
        run: |
          VERSION=$(grep -m 1 "version:" dozzle/config.yaml | awk '{print $2}' | tr -d "'")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Install Cosign and Skopeo
        run: |
          wget "https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64"
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign
          sudo apt-get update && sudo apt-get install -y skopeo
  

      - name: Generate key pair
        id: keys
        run: |
          cosign generate-key-pair
          echo "key_generated=true" >> $GITHUB_ENV

      - name: List available images
        run: |
          echo "Checking available images for version ${{ env.VERSION }}"
          for arch in amd64 aarch64 armv7; do
            echo "Checking $arch..."
            skopeo list-tags docker://ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-$arch || true
          done

      - name: Get image digest
        run: |
          for arch in amd64 aarch64 armv7; do
            echo "Processing architecture: $arch"
            IMAGE="ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-$arch:${{ env.VERSION }}"
            echo "Checking image: $IMAGE"
            
            # Try to get manifest first
            skopeo inspect docker://$IMAGE --raw || true
            
            # Then try to get digest
            DIGEST=$(skopeo inspect docker://$IMAGE --format '{{.Digest}}' || true)
            
            if [ -z "$DIGEST" ]; then
              echo "Error: No image found for architecture $arch"
              echo "Full image details:"
              skopeo inspect docker://$IMAGE || true
              exit 1
            fi
            
            arch_upper=$(echo $arch | tr '[:lower:]' '[:upper:]')
            echo "DOZZLE_${arch_upper}_DIGEST=$DIGEST" >> $GITHUB_ENV
            echo "Found digest for $arch: $DIGEST"
          done

      - name: Sign images
        if: env.key_generated == 'true'
        run: |
          for arch in amd64 aarch64 armv7; do
            arch_upper=$(echo $arch | tr '[:lower:]' '[:upper:]')
            digest_var="DOZZLE_${arch_upper}_DIGEST"
            echo "Signing image for $arch with digest ${!digest_var}"
            cosign sign --key cosign.key \
              ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-$arch@${!digest_var}
          done

      - name: Upload public key
        if: env.key_generated == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cosign-public-key
          path: cosign.pub
          retention-days: 5