name: Sign Docker Images

on:
  workflow_run:
    workflows: ["Build and Push Multi-arch Docker Images"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: erreur32/homeassistant-dozzle-addon

jobs:
  sign-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from config.yaml
        id: version
        run: |
          VERSION=$(grep -m 1 "version:" dozzle/config.yaml | awk '{print $2}' | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.0'

      - name: Generate Key Pair
        id: generate_key
        run: |
          cosign generate-key-pair github://${{ github.repository }}
          echo "PUBLIC_KEY=$(cat cosign.pub)" >> $GITHUB_OUTPUT

      - name: Sign Images
        env:
          COSIGN_PASSWORD: ${{ steps.generate_key.outputs.key-password }}
        run: |
          # Signer toutes les images avec la version correcte
          for arch in amd64 aarch64 armv7; do
            cosign sign --key cosign.key \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/dozzle-$arch:${{ env.VERSION }}
            echo "Image $arch signée avec succès"
          done 