name: Sign Docker Images

on:
  workflow_run:
    workflows: ["Builder"]
    types:
      - completed

jobs:
  sign-images:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: 'v2.2.0'

      - name: Generate Key Pair
        id: generate_key
        run: |
          cosign generate-key-pair
          echo "PUBLIC_KEY=$(cat cosign.pub)" >> $GITHUB_OUTPUT
          echo "KEY_PASSWORD=${{ secrets.COSIGN_PASSWORD }}" >> $GITHUB_OUTPUT

      - name: Sign Images
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: |
          cosign sign --key cosign.key \
            ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-amd64:$GITHUB_SHA

          cosign sign --key cosign.key \
            ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-aarch64:$GITHUB_SHA

          cosign sign --key cosign.key \
            ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-armv7:$GITHUB_SHA
