name: Sign Docker Images

on:
  workflow_run:
    workflows: ["Build and Push Multi-arch Docker Images"]
    types:
      - completed

jobs:
  sign:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from config.yaml
        id: version
        run: |
          VERSION=$(grep -m 1 "version:" dozzle/config.yaml | awk '{print $2}' | tr -d "'")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Extracted version: $VERSION"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.3.0

      - name: Generate key pair
        run: |
          cosign generate-key-pair
          echo "PUBLIC_KEY=$(cat cosign.pub)" >> $GITHUB_OUTPUT

      - name: Sign images
        run: |
          for arch in amd64 aarch64 armv7; do
            cosign sign --key cosign.key \
              ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-$arch:${{ env.VERSION }}
            cosign sign --key cosign.key \
              ghcr.io/erreur32/homeassistant-dozzle-addon/dozzle-$arch:latest
          done

      - name: Upload public key
        uses: actions/upload-artifact@v4
        with:
          name: cosign-public-key
          path: cosign.pub
          retention-days: 5
